// Generated by Framer (ba156f5)
// Source: https://framer.com/m/Sound-Deck-9Rfp.js@ZHOAoUcciAFfmcfJcTIo

import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    RichText,
    SmartComponentScopedContainer,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCodeBoundaryForOverrides,
    withCSS
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";

// External dependencies (these would need to be available)
// import FollowCursor from "https://framerusercontent.com/modules/QbIURI1CrWibjjH7k1PR/2vNdLnvQNPcA8uP12d7k/FollowCursor_Prod.js";
// import { withDiscreteKnob } from "https://framerusercontent.com/modules/e4eqSvuXxUp3rSYG8IWe/vMbFueVh3Bp8dy3GZUmU/C5.js";
// import MicButton from "https://framerusercontent.com/modules/7BKU6LHB1NZ9aHk9P0cA/T8zFUZgiy882rq9EBVdG/RIjG7jmSE.js";
// import FXButton from "https://framerusercontent.com/modules/gVaL9dWGLLYVt1ZFSYkJ/IiAbLDpr76ETyHLrQoef/to1Q2Xtjb.js";

const serializationHash = "framer-uJDO0";
const variantClassNames = { IKGZIc_FN: "framer-v-38rqse" };

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}

const transition1 = { bounce: .2, delay: 0, duration: .4, type: "spring" };
const transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;

const Transition = ({ value, children }) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ?? config.transition;
    const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
    return /*#__PURE__*/_jsx(MotionConfigContext.Provider, { value: contextValue, children: children });
};

const Variants = motion.create(React.Fragment);

const getProps = ({ click, height, id, width, ...props }) => {
    return { ...props, YvqV6OuC9: click ?? props.YvqV6OuC9 };
};

const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};

const Component = /*#__PURE__*/React.forwardRef(function (props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ?? fallbackRef;
    const defaultLayoutId = React.useId();
    const { activeLocale, setLocale } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const { style, className, layoutId, variant, YvqV6OuC9, ...restProps } = getProps(props);
    const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({
        defaultVariant: "IKGZIc_FN",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant);
    const lfcUKy1jVqa5dd1 = activeVariantCallback(async (...args) => {
        if (YvqV6OuC9) {
            const res = await YvqV6OuC9(...args);
            if (res === false) return false;
        }
    });

    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);

    return /*#__PURE__*/_jsx(LayoutGroup, {
        id: layoutId ?? defaultLayoutId, children: /*#__PURE__*/_jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/_jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/_jsxs(motion.div, {
                    ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-38rqse", className, classNames),
                    "data-framer-name": "Sound Deck",
                    layoutDependency: layoutDependency,
                    layoutId: "IKGZIc_FN",
                    ref: refBinding,
                    style: {
                        borderBottomLeftRadius: 20,
                        borderBottomRightRadius: 20,
                        borderTopLeftRadius: 20,
                        borderTopRightRadius: 20,
                        ...style
                    },
                    children: [
                        // Behind Part
                        /*#__PURE__*/_jsx(motion.div, {
                        className: "framer-4ghb2d",
                        "data-framer-name": "Behind Part",
                        layoutDependency: layoutDependency,
                        layoutId: "KCbdPLQOY",
                        style: {
                            backgroundColor: "rgb(24, 27, 36)",
                            borderBottomLeftRadius: 20,
                            borderBottomRightRadius: 20,
                            borderTopLeftRadius: 20,
                            borderTopRightRadius: 20,
                            boxShadow: "inset 0px 2px 2px 4px rgba(39, 42, 51, 0.86)"
                        }
                    }),
                        // Upper Part with controls
                        /*#__PURE__*/_jsxs(motion.div, {
                        className: "framer-qqh9y3",
                        "data-framer-name": "Upper Part",
                        layoutDependency: layoutDependency,
                        layoutId: "wTCP48hFq",
                        style: {
                            background: "linear-gradient(180deg, rgb(31, 33, 38) 0%, rgb(41, 44, 51) 100%)",
                            borderBottomLeftRadius: 20,
                            borderBottomRightRadius: 20,
                            borderTopLeftRadius: 20,
                            borderTopRightRadius: 20,
                            boxShadow: "inset 0px 1px 1px 0px rgba(184, 184, 184, 0.1), inset 0px -1px 1px 0px rgb(61, 64, 71)"
                        },
                        children: [
                                // Inside controls container
                                /*#__PURE__*/_jsxs(motion.div, {
                            className: "framer-pkkb93",
                            "data-framer-name": "Inside",
                            layoutDependency: layoutDependency,
                            layoutId: "ItGTWn5Mz",
                            style: {
                                backgroundColor: "rgb(13, 13, 13)",
                                borderBottomLeftRadius: 11,
                                borderBottomRightRadius: 11,
                                borderTopLeftRadius: 11,
                                borderTopRightRadius: 11,
                                boxShadow: "0px 0px 4px 0px rgba(199, 199, 199, 0.12)"
                            },
                            children: [
                                        // Mic section - Note: MicButton component dependency
                                        /*#__PURE__*/_jsxs(motion.div, {
                                className: "framer-rz1yz5",
                                "data-framer-name": "Mic",
                                layoutDependency: layoutDependency,
                                layoutId: "mJzoT3_bv",
                                style: {
                                    borderBottomLeftRadius: 10,
                                    borderBottomRightRadius: 10,
                                    borderTopLeftRadius: 10,
                                    borderTopRightRadius: 10
                                },
                                children: [
                                                // MicButton would go here
                                                /*#__PURE__*/_jsx("div", {
                                    className: "framer-1uqph7j-container",
                                    children: "MIC BUTTON PLACEHOLDER"
                                }),
                                                // Highlight effect
                                                /*#__PURE__*/_jsx(motion.div, {
                                    className: "framer-14k4k3z",
                                    "data-framer-name": "Highlight",
                                    layoutDependency: layoutDependency,
                                    layoutId: "DFY2CMxh_",
                                    style: {
                                        background: "radial-gradient(50% 50% at 50% 50%, rgb(134, 143, 191) 0%, rgba(255, 255, 255, 0) 100%)",
                                        borderBottomLeftRadius: 10,
                                        borderBottomRightRadius: 10,
                                        borderTopLeftRadius: 10,
                                        borderTopRightRadius: 10,
                                        filter: "blur(11px)",
                                        opacity: .1,
                                        WebkitFilter: "blur(11px)"
                                    }
                                })
                                ]
                            }),
                                        // FX section
                                        /*#__PURE__*/_jsxs(motion.div, {
                                className: "framer-18m7549",
                                "data-framer-name": "FX",
                                layoutDependency: layoutDependency,
                                layoutId: "qnoZhyqt9",
                                style: {
                                    borderBottomLeftRadius: 10,
                                    borderBottomRightRadius: 10,
                                    borderTopLeftRadius: 10,
                                    borderTopRightRadius: 10
                                },
                                children: [
                                                /*#__PURE__*/_jsx("div", {
                                    className: "framer-3m2lwe-container",
                                    children: "FX BUTTON PLACEHOLDER"
                                }),
                                                /*#__PURE__*/_jsx(motion.div, {
                                    className: "framer-1jgbcxf",
                                    "data-framer-name": "Highlight",
                                    layoutDependency: layoutDependency,
                                    layoutId: "GjHdckoLB",
                                    style: {
                                        background: "radial-gradient(50% 50% at 50% 50%, rgb(134, 143, 191) 0%, rgba(255, 255, 255, 0) 100%)",
                                        borderBottomLeftRadius: 10,
                                        borderBottomRightRadius: 10,
                                        borderTopLeftRadius: 10,
                                        borderTopRightRadius: 10,
                                        filter: "blur(11px)",
                                        opacity: .1,
                                        WebkitFilter: "blur(11px)"
                                    }
                                })
                                ]
                            }),
                                        // EQ section
                                        /*#__PURE__*/_jsxs(motion.div, {
                                className: "framer-15rxvj2",
                                "data-framer-name": "EQ",
                                layoutDependency: layoutDependency,
                                layoutId: "PfsOarYAw",
                                style: {
                                    backgroundColor: "rgb(17, 18, 23)",
                                    borderBottomLeftRadius: 10,
                                    borderBottomRightRadius: 10,
                                    borderTopLeftRadius: 10,
                                    borderTopRightRadius: 10,
                                    boxShadow: "inset 0px 1px 0px 0px rgb(31, 31, 48), inset 0px -1px 0px 0px rgb(31, 31, 48), inset 0px 0px 19px 0px rgba(51, 51, 51, 0.2)"
                                },
                                children: [
                                                /*#__PURE__*/_jsxs(motion.div, {
                                    className: "framer-luajed",
                                    "data-framer-name": "Inside EQ",
                                    layoutDependency: layoutDependency,
                                    layoutId: "YkKln4B7c",
                                    children: [
                                                        /*#__PURE__*/_jsx(motion.p, {
                                        className: "framer-12fgevc",
                                        style: {
                                            "--framer-font-size": "20px",
                                            "--framer-text-color": "rgb(75, 77, 87)",
                                            color: "rgb(75, 77, 87)"
                                        },
                                        children: "EQ"
                                    }),
                                                        /*#__PURE__*/_jsx(motion.div, {
                                        className: "framer-8ahznr",
                                        "data-framer-name": "Inner Black Housing",
                                        layoutDependency: layoutDependency,
                                        layoutId: "RyOQaFf7J",
                                        style: {
                                            backgroundColor: "rgb(4, 5, 7)",
                                            borderRadius: 352,
                                            boxShadow: "inset 0px -1px 1px 0px rgb(34, 35, 38), inset 0px 1px 1px 0px rgb(34, 35, 38)"
                                        }
                                    }),
                                                        // EQ marks
                                                        /*#__PURE__*/_jsx(motion.div, {
                                        className: "framer-1c4l26u",
                                        "data-framer-name": "Top Mark",
                                        style: { backgroundColor: "rgb(58, 61, 79)" }
                                    }),
                                                        /*#__PURE__*/_jsx(motion.div, {
                                        className: "framer-1kbu4hz",
                                        "data-framer-name": "Right Mark",
                                        style: { backgroundColor: "rgb(58, 61, 79)", rotate: -90 }
                                    }),
                                                        /*#__PURE__*/_jsx(motion.div, {
                                        className: "framer-1l6jlne",
                                        "data-framer-name": "Left Mark",
                                        style: { backgroundColor: "rgb(58, 61, 79)", rotate: -90 }
                                    })
                                    ]
                                }),
                                                // Volume Knob
                                                /*#__PURE__*/_jsx(motion.div, {
                                    className: "framer-1p4pdlw",
                                    "data-framer-name": "Volume Knob",
                                    style: {
                                        background: "linear-gradient(180deg, rgb(30, 29, 35) 0%, rgb(30, 30, 38) 100%)",
                                        borderRadius: 352,
                                        boxShadow: "inset 0px -1px 1px 0px rgb(34, 35, 38), inset 0px 1px 1px 0px rgb(34, 35, 38), inset 0px 4px 8px 0px rgba(0, 0, 0, 0.47)"
                                    },
                                    children: /*#__PURE__*/_jsxs(motion.div, {
                                        className: "framer-1kzrvxn",
                                        "data-framer-name": "Knob Line",
                                        children: [
                                                            /*#__PURE__*/_jsx(motion.div, {
                                            className: "framer-1afhilt",
                                            style: { borderRadius: "50%" }
                                        }),
                                                            /*#__PURE__*/_jsx(motion.div, {
                                            className: "framer-duk42k",
                                            "data-framer-name": "line",
                                            style: {
                                                backgroundColor: "rgb(255, 111, 0)",
                                                borderRadius: 20,
                                                boxShadow: "inset 0px 1px 0px 2px rgb(240, 126, 46), 0px 1px 4px 0px rgba(240, 151, 67, 0.73)"
                                            }
                                        })
                                        ]
                                    })
                                })
                                ]
                            })
                            ]
                        }),
                                // Highlight overlay
                                /*#__PURE__*/_jsx(motion.div, {
                            className: "framer-znwl7e",
                            "data-framer-name": "Highlight",
                            style: {
                                backgroundColor: "rgba(48, 49, 51, 0.61)",
                                filter: "blur(9px)",
                                opacity: .98
                            }
                        })
                        ]
                    })
                    ]
                })
            })
        })
    });
});

const css = [
    "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
    ".framer-uJDO0.framer-rcqni9, .framer-uJDO0 .framer-rcqni9 { display: block; }",
    ".framer-uJDO0.framer-38rqse { height: 295px; overflow: hidden; position: relative; width: 128px; will-change: var(--framer-will-change-override, transform); }",
    ".framer-uJDO0 .framer-4ghb2d { flex: none; height: 280px; left: calc(50.00000000000002% - 126px / 2); overflow: hidden; position: absolute; top: calc(51.864406779661046% - 280px / 2); width: 126px; }",
    ".framer-uJDO0 .framer-qqh9y3 { flex: none; height: 286px; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; }",
    ".framer-uJDO0 .framer-pkkb93 { flex: none; height: 267px; left: calc(50.00000000000002% - 108px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 267px / 2); width: 108px; z-index: 2; }",
    ".framer-uJDO0 .framer-rz1yz5 { bottom: 2px; flex: none; height: 73px; left: calc(50.00000000000002% - 100px / 2); overflow: hidden; position: absolute; width: 100px; }",
    ".framer-uJDO0 .framer-1uqph7j-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; }",
    ".framer-uJDO0 .framer-14k4k3z, .framer-uJDO0 .framer-1jgbcxf { flex: none; height: 57px; left: calc(50.00000000000002% - 82px / 2); overflow: hidden; pointer-events: none; position: absolute; top: calc(49.27536231884061% - 57px / 2); width: 82px; z-index: 2; }",
    ".framer-uJDO0 .framer-18m7549 { bottom: 80px; flex: none; height: 69px; left: calc(50.00000000000002% - 100px / 2); overflow: hidden; position: absolute; width: 100px; }",
    ".framer-uJDO0 .framer-3m2lwe-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; z-index: 0; }",
    ".framer-uJDO0 .framer-15rxvj2 { flex: none; height: 109px; left: calc(50.00000000000002% - 100px / 2); overflow: hidden; position: absolute; top: 4px; width: 100px; }",
    ".framer-uJDO0 .framer-luajed { flex: none; height: 103px; left: calc(50.00000000000002% - 82px / 2); overflow: hidden; position: absolute; top: calc(48.648648648648674% - 103px / 2); width: 82px; z-index: 6; }",
    ".framer-uJDO0 .framer-12fgevc { bottom: 0px; flex: none; height: auto; left: 50%; position: absolute; white-space: pre; width: auto; }",
    ".framer-uJDO0 .framer-8ahznr { flex: none; height: 66px; left: calc(50.00000000000002% - 65px / 2); overflow: hidden; position: absolute; top: 8px; width: 65px; }",
    ".framer-uJDO0 .framer-1c4l26u { flex: none; height: 4px; left: calc(50.00000000000002% - 1px / 2); overflow: hidden; position: absolute; top: 2px; width: 1px; }",
    ".framer-uJDO0 .framer-1kbu4hz { flex: none; height: 4px; left: 77px; overflow: hidden; position: absolute; top: 39px; width: 1px; }",
    ".framer-uJDO0 .framer-1l6jlne { flex: none; height: 4px; left: 4px; overflow: hidden; position: absolute; top: 39px; width: 1px; }",
    ".framer-uJDO0 .framer-1p4pdlw { flex: none; height: 52px; left: calc(50.00000000000002% - 51px / 2); overflow: hidden; position: absolute; top: 16px; width: 51px; z-index: 6; }",
    ".framer-uJDO0 .framer-1kzrvxn { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; }",
    ".framer-uJDO0 .framer-1afhilt { bottom: 0px; flex: none; left: 0px; overflow: hidden; position: absolute; right: 0px; top: 0px; z-index: -1; }",
    ".framer-uJDO0 .framer-duk42k { flex: none; height: 8px; left: calc(50.98039215686276% - 2px / 2); overflow: hidden; position: absolute; top: 6px; width: 2px; }",
    ".framer-uJDO0 .framer-znwl7e { flex: none; height: 58px; overflow: hidden; position: absolute; right: -30px; top: 44px; width: 70px; z-index: 0; }"
];

// NOTE: This component requires the Framer library and won't work standalone
// It has dependencies on:
// - framer (core library)
// - MicButton, FXButton, FollowCursor (external Framer components)
// This file is saved for reference. Use the iframe embedding method instead.

export default Component;
